- hosts: localhost
  user: ubuntu
  sudo: yes
  tasks:
  - name copy and run the basic installation script
    copy: src:ansibleinstall.sh dest: /home/ubuntu mode: 0511
    
  - name: run a script
    command: ./ansibleinstall.sh
    
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: apt update
    apt: update_cache=yes
    tag: update
  
  - name: Install list of packages
    tag: install
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
